apiVersion: v1
kind: Pod
metadata:
  name: client-pod
  labels:
    component: web
spec:
  containers:
    - name: client
      image: horatiuandrei/multi-client
      ports:
        - containerPort: 3000

# kubectl apply -f client-pod.yaml
# kubectl apply -f client-node-port.yaml
# kubectl get pods
# kubectl get pods -o wide
# kubectl describe pod client-pod
# kubectl describe pod
# kubectl delete -f client-pod.yaml
# kubectl get deployments
# kubectl set image deployment/client-deployment client=horatiuandrei/multi-client:v2
