name: Deploy MultiDocker
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Docker Login (Action)
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      # - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - run: docker build -t horatiuandrei/react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true horatiuandrei/react-test npm test

      - run: docker build -t horatiuandrei/multi-client ./client
      - run: docker build -t horatiuandrei/multi-nginx ./nginx
      - run: docker build -t horatiuandrei/multi-server ./server
      - run: docker build -t horatiuandrei/multi-worker ./worker

      - run: docker push horatiuandrei/multi-client
      - run: docker push horatiuandrei/multi-nginx
      - run: docker push horatiuandrei/multi-server
      - run: docker push horatiuandrei/multi-worker

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: udemy-docker-kubernetes-multi-docker
          environment_name: Udemy-docker-kubernetes-multi-do-env
          existing_bucket_name: elasticbeanstalk-ap-southeast-1-208838686419
          region: ap-southeast-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip