# Auth to Google Cloud using Workload Identity Federation
name: Deploy MultiK8s - Workload Identity Federation
# run: exit 1
on:
  push:
    branches:
      - main

env:
  SHA: $(git rev-parse HEAD)

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - uses: actions/checkout@v3

      - name: Docker Login (Action)
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      # - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Test
        run: |-
          docker build -t horatiuandrei/react-test -f ./client/Dockerfile.dev ./client
          docker run -e CI=true horatiuandrei/react-test npm test

      - name: Google Cloud -> Set Identity Provider
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: 'projects/731457015652/locations/global/workloadIdentityPools/github/providers/my-repo'
          service_account: 'github-actions-deployer@udemy-docker-kubernetes-m-k8s.iam.gserviceaccount.com'

      - name: Google Cloud -> Set Project
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
          project_id: udemy-docker-kubernetes-m-k8s

      - name: Google Cloud -> Auth
        run: |-
          gcloud --quiet auth configure-docker

      - name: Google Cloud -> Get Credentials
        uses: 'google-github-actions/get-gke-credentials@v2'
        with:
          cluster_name: multi-cluster
          location: asia-south1-a

      - name: Build
        run: |-
          docker build -t horatiuandrei/multi-client:latest -t horatiuandrei/multi-client:${{ env.SHA }} -f ./client/Dockerfile ./client
          docker build -t horatiuandrei/multi-server:latest -t horatiuandrei/multi-server:${{ env.SHA }} -f ./server/Dockerfile ./server
          docker build -t horatiuandrei/multi-worker:latest -t horatiuandrei/multi-worker:${{ env.SHA }} -f ./worker/Dockerfile ./worker

      - name: Push
        run: |-
          docker push horatiuandrei/multi-client:latest
          docker push horatiuandrei/multi-server:latest
          docker push horatiuandrei/multi-worker:latest
          
          docker push horatiuandrei/multi-client:${{ env.SHA }}
          docker push horatiuandrei/multi-server:${{ env.SHA }}
          docker push horatiuandrei/multi-worker:${{ env.SHA }}

      - name: Apply
        run: |-
          kubectl apply -f k8s
          kubectl set image deployments/client-deployment client=horatiuandrei/multi-client:${{ env.SHA }}
          kubectl set image deployments/server-deployment server=horatiuandrei/multi-server:${{ env.SHA }}
          kubectl set image deployments/worker-deployment worker=horatiuandrei/multi-worker:${{ env.SHA }}